---
title: "Acerv_YII"
author: "AnaPalacioAndIsoppopers"
date: "April 5, 2017"
output: html_document
---

  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```


# General project set-up 

```{r libraries, results="hide"}

getwd()

# Get all libraries and sources required to run the script

library(dplyr)
library(plyr)
library(reshape2)
library(ggplot2)

Acer.data<-read.csv("Data_YII.csv") 


YII <- ggplot(Acer.data, aes (Time, Y.II., colour=factor(Colony)))
YII + stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2)+
  stat_summary(fun.y=mean, geom="point", size =3, alpha=0.5) +
 # geom_jitter()+
  facet_wrap(~Treatment)


YII <- ggplot(Acer.data, aes (Time, Y.II., colour=factor(Treatment)))
YII + stat_summary(fun.data = "mean_cl_boot",geom = "errorbar", width = 0.2)+
  stat_summary(fun.y=mean, geom="point", size =3, alpha=0.5)
# geom_jitter()+
# facet_wrap(~Time)

Time4<-Acer.data[which(Acer.data$Time==4), ]
  
Time4$Treatment <- factor(Time4$Treatment)
  
ANOVA_Y <- aov(Y.II.~Treatment*Colony, Time4)
summary(ANOVA_Y)
plot(ANOVA_Y)

TukeyHSD (aov(Y.II.~Treatment, Time4))

```
